#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 4, rgba8_snorm) uniform restrict image2D uMyImage;

void main()
{
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy); // e.g., ivec2(1920, 1080)
    vec4 colorIn = imageLoad(uMyImage, coords).rgba;
    vec4 colorOut = colorIn * vec4(0.0, 1.0, 0.0, 1.0);
    imageStore(uMyImage, coords, colorOut);
}